# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://47.110.132.41:3306/oursudoku
    username: root
    password: seg02
  security:
    user:
      name: user
      password: pwd
      roles: zx
server:
  port: 8081


